### PR TITLE
annotation error fixes; unsure about lines 987 and 1429-1433

### PR DESCRIPTION
**Pull request by alexisjihyeross**

### CODE REVIEW

**Comment by matt-gardner** [comment]
@pmulcaire, can you take a quick look at these and let us know what you think?  @alexisjihyeross was working on a related project and found what appeared to be some minor annotation errors.  Do you agree with these fixes?

There's no particular rush here; don't worry about responding before the EMNLP deadline if you're busy.

**Comment by pmulcaire** [comment]
The fixes look correct to me, including for the noun phrases in lines 987 and 1429-1433 (though I agree those are tricky).

**Comment by pmulcaire** [comment]
Thank you for catching these @alexisjihyeross !

**Comment by matt-gardner** [comment]
Thanks @pmulcaire!

**Pull request merged**
